---
title: "Linear Mixed Model Zeng el al"
output: html_notebook
---
position the caret at any line or the code chunk, then click "+".

The code chunk appears:
```{r}
library(car)             # Load he car package for leveneTest
library(lmerTest)
library(haven)
library(tidyverse)
library(RColorBrewer)
library(lme4)
library(lmtest)
library(flexplot)
library(dplyr)
```

Type any R code in the chunk, for example:
```{r}
data_both_pall <- read.csv('/Users/aryal/Desktop/ForeCache/foreCache-interaction/ForeCache_Models/data/zheng/mixed-model-data/zheng_both_datasets.csv', stringsAsFactors = TRUE)
data_both_pall$u <- as.factor(data_both_pall$u)
data_both_pall$Task <- as.factor(data_both_pall$Task)
data_both_pall$Trial <- as.factor(data_both_pall$Trial)
data_both_pall$Openend <- as.factor(data_both_pall$Openend)
data_both_pall$Dataset <- as.factor(data_both_pall$Dataset)
#combine 2 variables and make a new
data_both_pall$OpenDataset <- paste(data_both_pall$Openend, data_both_pall$Dataset, sep = "_")
```
```{r}
#response ~ Trial + (1 | u) + (1 | Task) + (1 | Dataset) + (1 | Experiment) + (1 | Openendedness)

combined_model_full_same <- lmer(formula = probabsame~ Trial + Openend + (1 | u) + (1 | Dataset)  , data = data_both_pall, REML = FALSE)
reducedmodel_same <- lmer(formula =  probabsame ~ 1 +Openend + (1 | u) + (1 | Dataset), data = data_both_pall, REML = FALSE)
lrtest(combined_model_full_same, reducedmodel_same)
```
```{r}
combined_model_reporting_same <-lmer(formula = probabsame~ Trial + Openend + (1 | u) + (1 | Dataset), data = data_both_pall)
summary(combined_model_reporting_same)
```
```{r}
shapiro.test(resid(combined_model_reporting_same))
qqnorm(resid(combined_model_reporting_same))
qqline(resid(combined_model_reporting_same))
```
```{r}
combined_model_full_modify1 <- lmer(formula = probabmodify1~ Trial + Openend + (1 | u) + (1 | Dataset) , data = data_both_pall, REML = FALSE)
reducedmodel_modify1 <- lmer(formula =  probabmodify1 ~ 1  + Openend + (1 | u) + (1 | Dataset), data = data_both_pall, REML = FALSE)
lrtest(reducedmodel_modify1, combined_model_full_modify1)
```
```{r}
combined_model_reporting_modify1 <-lmer(formula = probabmodify1~ Trial + Openend + (1 | u) + (1 | Dataset), data = data_both_pall)
summary(combined_model_reporting_modify1)
```
```{r}
shapiro.test(resid(combined_model_reporting_modify1))
qqnorm(resid(combined_model_reporting_modify1))
qqline(resid(combined_model_reporting_modify1))
```
```{r}
combined_model_full_modify2 <- lmer(formula = probabmodify2~Trial + Openend + (1 | u) + (1 | Dataset), data = data_both_pall, REML = FALSE)
reducedmodel_modify2 <- lmer(formula =  probabmodify2 ~ 1  + Openend + (1 | u) + (1 | Dataset), data = data_both_pall, REML = FALSE)
lrtest(reducedmodel_modify2, combined_model_full_modify2)
```
```{r}
combined_model_reporting_modify2 <-lmer(formula = probabmodify2~ Trial + Openend + (1 | u) + (1 | Dataset), data = data_both_pall)
summary(combined_model_reporting_modify2)
```
```{r}
shapiro.test(resid(combined_model_reporting_modify2))
qqnorm(resid(combined_model_reporting_modify2))
qqline(resid(combined_model_reporting_modify2))
```

```{r}
combined_model_full_modify3 <- lmer(formula = probabmodify3~ Trial + Openend + (1 | u) + (1 | Dataset), data = data_both_pall, REML = FALSE)
reducedmodel_modify3 <- lmer(formula =  probabmodify3 ~ 1 + Openend + (1 | u) + (1 | Dataset), data = data_both_pall, REML = FALSE)
lrtest(reducedmodel_modify3, combined_model_full_modify3)
```
```{r}
combined_model_reporting_modify3 <-lmer(formula = probabmodify3~ Trial + Openend+ (1 | u) + (1 | Dataset), data = data_both_pall)
summary(combined_model_reporting_modify3)
```
```{r}
shapiro.test(resid(combined_model_reporting_modify3))
qqnorm(resid(combined_model_reporting_modify3))
qqline(resid(combined_model_reporting_modify3))
```

Now, click the **Run** button on the chunk toolbar to [execute](https://www.jetbrains.com/help/pycharm/r-markdown.html#run-r-code) the chunk code. The result should be placed under the chunk.
Click the **Knit and Open Document** to build and preview an output.
