---
title: "Linear Mixed Model Zeng el al"
output: html_notebook
---
position the caret at any line or the code chunk, then click "+".

The code chunk appears:
```{r}
library(car)             # Load the car package for leveneTest
library(lmerTest)
library(haven)
library(tidyverse)
library(RColorBrewer)
library(lme4)
library(lmtest)
library(flexplot)
library(dplyr)
```

Type any R code in the chunk, for example:
```{r}
data_both_pall <- read.csv('/Users/aryal/Desktop/ForeCache/foreCache-interaction/ForeCache_Models/data/zheng/mixed-model-data/zheng_both_datasets_combined.csv', stringsAsFactors = TRUE)
data_both_pall$u <- as.factor(data_both_pall$u)
data_both_pall$Dataset <- as.factor(data_both_pall$Dataset)
data_both_pall$Openended <- as.factor(data_both_pall$Openended)
```
```{r}
combined_model_full_same <- lmer(formula = probabsame~ Trial   + Openended + (1|Dataset)  + (1|u), data = data_both_pall, REML = FALSE)
reducedmodel_same <- lmer(formula =  probabsame ~ 1  +Openended+ (1|Dataset)+ (1|u), data = data_both_pall, REML = FALSE)
lrtest(reducedmodel_same, combined_model_full_same)
```
```{r}
combined_model_reporting_same <-lmer(formula = probabsame~Trial   + (1|Openended)  + (1|u), data = data_both_pall)
summary(combined_model_reporting_same)
```
```{r}
shapiro.test(resid(combined_model_reporting_same))
qqnorm(resid(combined_model_reporting_same))
qqline(resid(combined_model_reporting_same))
```
```{r}
combined_model_full_modify1 <- lmer(formula = probabmodify1~ Trial  + (1|Dataset) + (1|u), data = data_both_pall, REML = FALSE)
reducedmodel_modify1 <- lmer(formula =  probabmodify1 ~ 1 + (1|Dataset)+ (1|u), data = data_both_pall, REML = FALSE)
lrtest(reducedmodel_modify1, combined_model_full_modify1)
```
```{r}
combined_model_reporting_modify1 <-lmer(formula = probabmodify1~ Trial + (1|Dataset)+ (1|u), data = data_both_pall)
summary(combined_model_reporting_modify1)
```
```{r}
shapiro.test(resid(combined_model_reporting_modify1))
qqnorm(resid(combined_model_reporting_modify1))
qqline(resid(combined_model_reporting_modify1))
```
```{r}
combined_model_full_modify2 <- lmer(formula = probabmodify2~ Trial  + (1|Dataset) + (1|u), data = data_both_pall, REML = FALSE)
reducedmodel_modify2 <- lmer(formula =  probabmodify2 ~ 1  + (1|Dataset)  + (1|u), data = data_both_pall, REML = FALSE)
lrtest(reducedmodel_modify2, combined_model_full_modify2)
```
```{r}
combined_model_reporting_modify2 <-lmer(formula = probabmodify2~ Trial + (1|Experiment) + (1|u), data = data_both_pall)
summary(combined_model_reporting_modify2)
```
```{r}
shapiro.test(resid(combined_model_reporting_modify2))
qqnorm(resid(combined_model_reporting_modify2))
qqline(resid(combined_model_reporting_modify2))
```

```{r}
combined_model_full_modify3 <- lmer(formula = probabmodify3~ Trial + (1|Dataset)+ (1|u), data = data_both_pall, REML = FALSE)
reducedmodel_modify3 <- lmer(formula =  probabmodify3 ~ 1 +  (1|Dataset)+(1|u), data = data_both_pall, REML = FALSE)
lrtest(reducedmodel_modify3, combined_model_full_modify3)
```
```{r}
combined_model_reporting_modify3 <-lmer(formula = probabmodify3~ Trial  + (1|Dataset) + (1|u), data = data_both_pall)
summary(combined_model_reporting_modify3)
```
```{r}
shapiro.test(resid(combined_model_reporting_modify3))
qqnorm(resid(combined_model_reporting_modify3))
qqline(resid(combined_model_reporting_modify3))
```

Now, click the **Run** button on the chunk toolbar to [execute](https://www.jetbrains.com/help/pycharm/r-markdown.html#run-r-code) the chunk code. The result should be placed under the chunk.
Click the **Knit and Open Document** to build and preview an output.
